### ISSUE TITLE
Crud vs CRUD

### ISSUE THREAD

**Issue by kaishin** [simonedelmann/crud-kit#1]
Hi Simon,

Kudos for the work! I think this is going to be very useful for quickly bootstrapping projects. I have some feedback about naming conventions in the API, however.

CRUD being an abbreviation, it looks a bit odd to spell it as `Crud`. If it's meant as a pun, then it's unfortunate that _crud_ in english has only negative connotations. I also think that the protocol name `Crudable` is, for lack of a better word, off-putting.

What do you think of the following?

```swift
import CRUDKit
extension Todo: CRUDModel { }
```

**Comment by simonedelmann** [comment]
Hey, thanks for your feedback!
As English is not my first language, naming things is always not easy for me. I will change this right now!

**Comment by simonedelmann** [comment]
...and done! Thanks again for your suggestion!

**Comment by kaishin** [comment]
Very glad you considered my suggestion. Looking forward to using this soon!
