### ISSUE TITLE
app.crud for longer endpoint

### ISSUE THREAD

**Issue by alazirakaclan** [simonedelmann/crud-kit#6]
I'd like to get responses on e.g. "/site/api/todos". And it seems it's not possible to do it right now, cause "app.crud(...)" accepts only one string. 

I thought about something like this:

`
extension RoutesBuilder {
    public func crud<T: Model & CRUDModel>(_ endpoints: [String], model: T.Type, custom: ((RoutesBuilder, CRUDController<T>) -> ())? = nil) where T.IDValue: LosslessStringConvertible {
        let endpoint = endpoints.last!
        let modelComponents = endpoints.map{endpoint in PathComponent(stringLiteral: endpoint)}
        let idComponents = modelComponents + [PathComponent(stringLiteral: ":\(endpoint)")]
 
        
        let routes = self.grouped(modelComponents)
        let idRoutes = routes.grouped(idComponents)
        
        let controller = CRUDController<T>(idComponentKey: endpoint)
        controller.setup(self, on: endpoint)
                
        custom?(idRoutes, controller)
    }
}
`

But I can't use it, because CRUDController<T> is internal.

**Comment by simonedelmann** [comment]
Thanks for your issue! If I understood correctly, you can - and should - use Vapors route groups for this. (See [here](https://docs.vapor.codes/4.0/routing/#route-groups))
```swift
let api = app.grouped("site", "api")
api.crud("todos", ...)
```
Anyhow I can make `CRUDController` public if you want to extend `RoutesBuilder` for this. Feel free to make a PR!

**Comment by simonedelmann** [comment]
@alazirakaclan Can I close this issue?
